### ISSUE TITLE
CPAN RT Tickets

### ISSUE THREAD

**Issue by eserte** [dacav/PFT#3]
Are you aware of the bugs reported at RT?
https://rt.cpan.org/Dist/Display.html?Name=PFT

**Comment by dacav** [comment]
Hello @eserte. Sorry for the late answer.
Yes, I'm aware of it.
It requires a bit of time and patience to find a solution.
The bug is btw caused by a situation which is not common in the use case, that is a system without encoding setted.
I'll investigate when I'll have time.
Thanks for the report :)

**Comment by dacav** [comment]
By the way, it is now patched. I'm closing this issue.
